version: "2"

services:
  zaizai-hadoop-1:
    image: zsyh/spark:2.1.1
    command: ["/usr/hadoop-2.7.3/etc/hadoop/master.sh"]
    hostname: zaizai-hadoop-1
    volumes:
      # - "./conf/hadoop:/usr/hadoop-2.7.3/etc/hadoop"
      # - "./conf/spark:/usr/spark-2.1.1/conf"
      - "/opt/hdfs:/opt/hdfs"
      - "/home/zaizai/data:/data"
    ports:
      - "4040:4040"
      - "4044:4044"
      - "6066:6066"
      - "7070:7070"
      - "7077:7077"
      - "8000:8000"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8042:8042"
      - "8080:8080"
      - "8088:8088"
      - "8090:8090"
      - "8480:8480"
      - "8481:8481"
      - "9000:9000"
      - "9001:9001"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "50091:50091"
      - "50100:50100"
      - "50105:50105"
      - "50470:50470"
      - "50475:50475"
  zaizai-hadoop-5:
    image: zsyh/spark:2.1.1
    command: ["/usr/hadoop-2.7.3/etc/hadoop/slave.sh"]
    hostname: zaizai-hadoop-5
    volumes:
      # - "./conf/hadoop:/usr/hadoop-2.7.3/etc/hadoop"
      # - "./conf/spark:/usr/spark-2.1.1/conf"
      - "/opt/hdfs1:/opt/hdfs"
    # environment:
    #   SPARK_WORKER_CORES: 4
    #   SPARK_WORKER_MEMORY: 3g
    # extra_hosts:
    #   - "zaizai-hadoop-1:172.6.22.1"
    links:
      - zaizai-hadoop-1


# deprecation
  # image: gettyimages/spark:2.1.1-hadoop-2.7
  # command: ["/usr/hadoop-2.7.3/sbin/hadoop-daemon.sh","start","namenode","&&","/usr/hadoop-2.7.3/sbin/yarn-daemon.sh","start","resourcemanager","&&"  ,"/usr/spark-2.1.1/bin/spark-class", "org.apache.spark.deploy.master.Master"]
  # command: ["/usr/spark-2.1.1/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  # worker:
  #   image: singularities/spark
  #   command: start-spark worker master
  #   volumes:
  #     - "/opt/hdfs/worker:/opt/hdfs/worker"
  #   environment:
  #     SPARK_WORKER_CORES: 1
  #     SPARK_WORKER_MEMORY: 2g
  #   links:
  #     - master
