version: "2"

services:
  zaizai-hadoop-6:
    image: zsyh/spark:2.1.1
    command: ["/usr/hadoop-2.7.3/etc/hadoop/slave.sh"]
    hostname: zaizai-hadoop-6
    volumes:
      - "/Users/oureda/hdfs:/opt/hdfs"
    # environment:
    #   SPARK_WORKER_CORES: 4
    #   SPARK_WORKER_MEMORY: 3g
    network_mode: "weave"
