version: "2"

services:
  zaizai-hadoop-1:
    image: zsyh/spark:2.1.1
    command: ["/usr/hadoop-2.7.3/etc/hadoop/master.sh"]
    hostname: zaizai-hadoop-1
    volumes:
      - "/opt/hdfs:/opt/hdfs"
      - "/home/zaizai/data:/data"
    network_mode: "weave"
